apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: promote-nodejs-app
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: image
        type: image
    params:
      - name: PROMOTE_ENVIRONMENT
        description: The environment where you deploy the app
        default: 'env-stage'
        type: string
  outputs:
    resources:
      - name: image
        type: image
  steps:
  #####将$(inputs.resources.image.url)tag成$(outputs.resources.image.url)（dev tag stage），并上传到镜像仓库
    - name: tag-image
      image: docker:dind
      args: ["tag","$(inputs.resources.image.url)","$(outputs.resources.image.url)"]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
          
    - name: push-new-image
      image: docker:dind
      args: ["push", "$(outputs.resources.image.url)"]
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

    - name: deploy-resources
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(inputs.resources.source.path)/ci-cd-pipeline/tekton-kubernetes/deploy-stage.yaml"
        - "-n"
        - "$(inputs.params.PROMOTE_ENVIRONMENT)"
    - name: deploy-application
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "rollout"
        - "restart"
        - "deployment/nodejs-app"
        - "-n"
        - "$(inputs.params.PROMOTE_ENVIRONMENT)"
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket